/**
 * Renders the model-facing tool catalog as Markdown, derived from the exact
 * `openAiTools` descriptors the agent loop sends (T9 of
 * docs/superpowers/specs/2026-08-13-dsh-borrowings-plan.md §10).
 *
 * Derived, never hand-kept: a hand-written list of tool descriptions is a
 * second copy of the schemas, and second copies drift. `scripts/gen-tool-catalog.ts`
 * writes this to `docs/tool-catalog.md`; its `--check` mode re-renders and
 * compares, so a schema edit that skips the regeneration fails loudly.
 *
 * MODEL EXPERIENCE: this module produces DOCUMENTATION about what the model
 * sees; nothing here reaches a model request. The schemas it describes do --
 * see `docs/model-context-inventory.md` §3.5.
 */

/** Placed at the top of the generated file; also what tests assert on. */
export const GENERATED_MARKER =
  "<!-- Generated by sidecar/scripts/gen-tool-catalog.ts — do not edit by hand. -->";

/** The one caveat a reader must not miss: this is not the full set. */
const MCP_CAVEAT =
  "This catalog covers OpenType's **built-in** tools only. Tools contributed by " +
  "user-configured MCP servers (`OPENTYPE_MCP_SERVERS`) are resolved at run time and " +
  "are therefore **not** listed here — the set the model actually sees is this list " +
  "plus whatever those servers contribute.";

interface FunctionDescriptor {
  name: string;
  description?: string;
  parameters?: unknown;
}

/**
 * Narrows one raw `openAiTools` entry, tolerating anything that is not a
 * well-formed function descriptor. The array is typed `unknown[]` at its
 * source and merges contributions from several tool sets, so a renderer that
 * threw on an unexpected entry would turn a doc-generation step into a
 * failure mode for the product's tool wiring.
 */
function functionOf(entry: unknown): FunctionDescriptor | undefined {
  if (!entry || typeof entry !== "object") {
    return undefined;
  }
  const fn = (entry as { function?: unknown }).function;
  if (!fn || typeof fn !== "object") {
    return undefined;
  }
  const name = (fn as { name?: unknown }).name;
  if (typeof name !== "string" || name.length === 0) {
    return undefined;
  }
  const description = (fn as { description?: unknown }).description;
  return {
    name,
    description: typeof description === "string" ? description : undefined,
    parameters: (fn as { parameters?: unknown }).parameters,
  };
}

function renderOne(fn: FunctionDescriptor): string {
  const lines = [`## \`${fn.name}\``, "", fn.description ?? "_No description._", ""];
  if (fn.parameters !== undefined) {
    lines.push("```json", JSON.stringify(fn.parameters, null, 2), "```", "");
  }
  return lines.join("\n");
}

/**
 * Render the catalog.
 *
 * @param openAiTools - the raw descriptors, exactly as sent to the model.
 * @returns Markdown; byte-stable for equivalent input, since `--check`
 *   compares whole files and input order is not meaningful (tool sets are
 *   merged from several sources), so entries are sorted by name.
 */
export function renderToolCatalog(openAiTools: readonly unknown[]): string {
  const functions = openAiTools
    .map(functionOf)
    .filter((fn): fn is FunctionDescriptor => fn !== undefined)
    .sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0));

  const header = [
    GENERATED_MARKER,
    "",
    "# Tool catalog",
    "",
    MCP_CAVEAT,
    "",
    `Built-in tools: **${functions.length}**.`,
    "",
  ];

  if (functions.length === 0) {
    return [...header, "No tools are registered in this build.", ""].join("\n");
  }

  return [...header, ...functions.map(renderOne)].join("\n");
}
